name: Post an Issue
description: Request a change to improve competition
title: "Issue Title"
labels: ["Status: Triage"]
body:
- type: textarea
  attributes:
    label: Description
    description: A more detailed description of the request - describe your use case, current blockers etc. If necessary you can link to supplementary documentation but make sure this section contains sufficient detail that readers can clearly understand the issue without referring to the external documentation.
  validations:
    required: true
- type: textarea
  attributes:
    label: Outcome
    description: What do you desire to see implemented to resolve your request. Where there are multiple possible remedies, list them and state any preference. List any success criteria where appropriate.
  validations:
    required: true
- type: markdown
  attributes:
      value: |
        ### CHECKLIST - Before Submitting:
        1. I am confident my issue is within scope based on the [Open Web Competition Platform's scope guidelines](https://github.com/OpenWebAdvocacy/OpenWebCompetitionPlatform?tab=readme-ov-file#scope).  
        2. I have searched to see that there is not already an existing issue
        3. I have added a "To: (Requestee)" label
        4. I have added a "Priority" label (if required)
        5. If you represent an organization, and have authorization from that organization to do so, add the label "Support: (Your Organization)" to the issue
